### ISSUE TITLE
investigate recent crashes

### ISSUE THREAD

**Issue by pkra** [boolesrings/boolesrings-base2#1]
For the past few days, the action in the main repo has crashed, e.g., https://github.com/boolesrings/boolesrings.org/actions/runs/4352144923/jobs/7604563427

Looks like a feed is broken.

**Comment by pkra** [comment]
It's Ioanna's. Looks like the feed is 404 gone (and basically the entire homepage).

I'll comment out the entry in app.js. I guess we should try/catch the feed parsing in generateEntries but it feels right to crash.

**Comment by pkra** [comment]
Nope, that was not enough.

**Comment by pkra** [comment]
Blorgh. Joel's feed is broken - ends with some open tags. 

try/catch it is then.

**Comment by scoskey** [comment]
Unclosed tags… gotcha.

**Comment by pkra** [comment]
Actions work again.

**Comment by scoskey** [comment]
You’re a whizzerd!
